### ISSUE TITLE
window.questions

### ISSUE THREAD

**Issue by FloppyT** [SnowLord7/Gimkit-Hack#1]
window.questions is not valid in a live game, and I don't think it ever will be. Window.questions is only valid is preview games.

**Comment by SnowLord7** [comment]
Thanks for telling me, I uploaded my testing one instead of the master.
I'll release the actual one this weekend.

**Comment by FloppyT** [comment]
Ok, good luck. 

P.S
I made a gimkit "hack" a while back, as a challenge but then gimkit added a no "reverse engineering" section to the terms. Caution with posting your script, the first script to reverse engineer gimkit was taken down.

**Comment by SnowLord7** [comment]
Same with Quizlet, would you mind sending me the ToS where it mentions it?

**Comment by FloppyT** [comment]
I think [Here](https://www.gimkit.com/pages/terms)

**Comment by SnowLord7** [comment]
Ok thanks, the wording in that part off the ToS is strange as you don't
reverse engineering websites.

**Comment by FloppyT** [comment]
Yeah, you're probably fine - I think it meant the backend blue boat stuff.

**Comment by FloppyT** [comment]
Sorry, i just noticed that window.questions isn't defined, I think you meant window.gameData.questions

**Comment by FloppyT** [comment]
Looks like you haven't found anything new for Gimkit. Here is a tip, learn how to use WebSockets, Gimkit's Blueboat server sends all the question data using some UTF8 and some other stuff.
