### ISSUE TITLE
Will there be a new version coming out anytime soon?

### ISSUE THREAD

**Issue by ThunderModsYT** [SnowLord7/Gimkit-Hack#10]
Title says it all, is it completely patched to the point that another hack like this can't be made anymore or there might be a chance in the future to see one of those things again?

**Comment by SnowLord7** [comment]
Making a cheat for Gimkit is very easy, preventing it from being patched is
not. If I release a new script it will most likely have to be a paid script
as I would be spending an absurdly large amount of time updating it.

**Comment by ThunderModsYT** [comment]
Sounds good to me, you should definitely make one, add me on discord? I will buy it right away! Also since it is java script, shouldn't there be a way for you to obfuscate it first and then release? Maybe it will help not getting patched very easily.

**Comment by ThunderModsYT** [comment]
Thunder Mods#0001 would be my discord just in case.
