### ISSUE TITLE
Not Working. Was working a week ago. Newer version needed.

### ISSUE THREAD

**Issue by slapsruler12** [SnowLord7/Gimkit-Hack#5]
Fails to underline answers and answer questions. [Saw you made a new commit called patched. RIP Gimkit script. Now I have to play legit. I wish you luck if you decide to try and work around their patch.]

**Comment by UndercoverGoose** [comment]
Gimkit deleted the kit ID from the JSON object, which is how these cheats actually get the answers to each question. The only way to get around this patch is to generate the kit ID from the question IDs, which I am currently working on doing.

**Comment by ajkachnic** [comment]
Do you have any idea of how the ID's are generated? 

Perhaps [this repo](https://github.com/gimkit/blueboat) might help

**Comment by ajkachnic** [comment]
I've found a possible solution. Given any question ID, this route returns the full kit object, however the user must be logged in or else you get an Unauthenticated error.

`https://www.gimkit.com/api/games/questions/search/<id>`

**Comment by ajkachnic** [comment]
After some investigation, these are all the API routes related to the game

```
/api/games/audio/add
/api/games/copy
/api/games/fetch/<id>
/api/games/image/add
/api/games/report
/api/games/search/<term>
/api/games/summary/me
/api/games/questions/search/<id>
```

**Comment by ajkachnic** [comment]
In the application store, the question ID and their correct answers are stored in 
`questions/answerMap`. However, I have no idea how to access the store in a script as I don't think it is global

**Comment by ajkachnic** [comment]
@SnowLord7  I can write an alternate way, retrieving the answers from the store and submit a pull request, if you'd like.

**Comment by Almedious** [comment]
@ajkachnic Have you made any progress on the gimkit script?

**Comment by Knocker379** [comment]
Yall are too smart 😂

**Comment by FloppyT** [comment]
There is a lot more API in gimkit. The only powerful way to create gimkit bot is with WebSockets, they allow for very powerful bots...

**Comment by UndercoverGoose** [comment]
The good thing is that some kits are still hackable. The ID's in these kits are all next to each other, as in you add 1 value to the hex number and you have the next question. If you grab the lowest number hex, and subtract 1 from it, youll have the kit ID. Problem is that some kits, these ID's seem randomized, but at least there is some light.

**Comment by Samuel-UC** [comment]
Late comment, but you should really just hook the websocket connection. Not only can you bypass the local anti-cheat but you can also easily get the answers to the questions.

Gimkit uses socket.io for handling the connections, which means you can use the socket.io debugger to view all outgoing and incoming messages. You can enable / disable the socket.io debugger with the following code snippet.
```js
let debugging = true;
debugging ? localStorage.setItem('debug', 'socket.io-client:socket') : localStorage.removeItem('debug');
```

If you want to encode / decode the websocket messages without socket.io you can use this [small library](https://github.com/Samuel-UC/msgpack)
