### ISSUE TITLE
Asks for code?

### ISSUE THREAD

**Issue by Knocker379** [SnowLord7/Gimkit-Hack#8]
I am trying to use the private.js but there is a password. Does that mean the code works, or are you giving the password out to people individually?

**Comment by slapsruler12** [comment]
Knocker379 I assume that is not a finalized version, or is being kept private to avoid skids from getting it patched from over using it. Just an assumption.

**Comment by ecc521** [comment]
@Knocker379 private.js is obfuscated, probably to make it harder to reverse engineer.

I also built a relatively similar gimkit-bot script (github.com/ecc521/gimkit-bot), and GimKit has repeatedly put in stupid little detection scripts for it using global variables. 

I've almost done the same. Not like I'm getting much help with it anyways. The loss of a bit of help is far outweighed by the inability of GimKit to reverse engineer.

**Comment by SnowLord7** [comment]
> In order to prevent Gimkit from constantly updating and implementing more anti-cheat features I decided to make the updated Gimkit script password protected to prevent Gimkit developers from easily viewing how the cheat works. I am currently only giving away access to the password through request.

It was a password encrypted version of the script which no longer works. I uploaded **not-private.js** with the unencrypted code in case anybody wants to see how it worked.
