### ISSUE TITLE
What happened SnowLord?

### ISSUE THREAD

**Issue by darthnithin** [SnowLord7/Gimkit-Hack#9]
### What happened SnowLord?
I know this isnt the right place but, what happened Snowlord? Why did you archive everything and basically stop everything? You don't have any contact links anywhere and you havent posted anything in the past 3 months. Y'd you archive the quizlet/developer tools github? Why'd you officially drop support for the extention? Please snowlord ... let us know why

**Comment by darthnithin** [comment]
Are you okay Drew?
[https://github.com/SnowLord7/quizlet/commit/f97326e8d94f0918e3c6788f69073629a0f3e266](https://github.com/SnowLord7/quizlet/commit/f97326e8d94f0918e3c6788f69073629a0f3e266)
`let index = 0,
                getId("js-learnModeAnswerButton").click();			phrases = 'Hello my friend you are you today? I am extremely sad because Quizlet finds enjoyment at my pain, not to mention they are being paid to make me sad while all I gain is depression.'.split(' ');`

**Comment by SnowLord7** [comment]
Thank you, I really appreciate the concern.

My life took a sudden turn in the last couple months and i've been having trouble dealing with it. Looking back on it, I acted in an extremely selfish way, I should not have suddenly archived the extension and removed all forms of contact. Even still, I can't help others when I can't even help myself.

Speaking plainly, I will most likely not come back here until I find out where I want to take my life.

**Comment by darthnithin** [comment]
Well good luck for the future... I hope things go well for you!
